icons_format = "{icon}"

[theme]
theme = "semi-native"

[icons]
icons = "awesome6"

[[block]]
block = "battery"
format = "bat: $percentage $power $time_remaining"
full_format = "bat: $percentage $power $time_remaining"
driver = "upower"

[[block]]
block = "cpu"
interval = 1
format = "dying cores: $utilization.eng(w:3) $frequency.eng(w:8, p:G)"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "load"
format = "load: $1m.eng(w:4)"
interval = 1

[[block]]
block = "memory"
format = "ram: $mem_total_used_percents.eng(w:2)"
format_alt = "swap: $swap_used_percents.eng(w:2)"

[[block]]
block = "temperature"
format = " $icon $max"
format_alt = "$icon $min min, $max max, $average avg"
interval = 10
chip = "*-isa-*"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "Anime: $available.eng(w:2)"

[[block]]
block = "net"
format = "{$signal_strength $ssid $frequency|Wired connection} via $device leaked $ip"
format_alt = "down: $speed_down.eng(prefix:K) up: $speed_up.eng(prefix:K)"
inactive_format = "NO INTERNET"

[[block]]
block = "sound"
format = "â™ª {$volume|}"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%Y-%m-%d %H:%M:%S')"
